development:
 adapter: mysql2
 database: linebyline1_development
 username: root
 password: root
 host: localhost
 port: ${3306}

test:
 adapter: mysql2
 database: linebyline1_test
 username: root
 password: root
 port: ${3306}

production:
 adapter: mysql2
 database: linebyline1_production
 username: root
 password: root
 port: ${3306}
